org.gradle.jvmargs=-Xmx2G

# Mod Info
maven_group = net.mifort
archives_base_name = testosterone
mod_version = 2.0.1

minecraft_version = 1.20.1

# Dependencies
# https://fabricmc.net/develop
fabric_loader_version = 0.17.2
fabric_api_version = 0.92.2+1.20.1

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment_version = 2023.09.03

# Create
# https://modrinth.com/mod/create-fabric/versions
create_version = 6.0.8.0+build.1734-mc1.20.1

# JEI - https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version = 15.49.0.188
trinkets_version = 3.7.0
# REI - https://modrinth.com/mod/rei/versions
rei_version = 12.0.626
# EMI - https://modrinth.com/mod/emi/versions
emi_version = 1.1.18+1.20.1

# Mod Menu - https://modrinth.com/mod/modmenu/versions
modmenu_version = 7.1.0
